[build]
  publish = "public"
  command = "npm i elm@latest && node scripts/generate-index.js && npx elm-spa build"

# Prevents missing markdown files from redirecting to index.html
[[redirects]]
  from = "/content/*"
  to = "/content/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200